repos:
  - repo: https://github.com/psf/black
    rev: 23.12.0  # Use the latest version of Black
    hooks:
      - id: black
        args: ["--line-length", "88"]  # Set the max line length

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --ignore=UP035]
        exclude: ^tests/
        additional_dependencies: ["ruff==0.2.1"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: debug-statements
